language: csharp
dist: trusty
sudo: false

mono: none
dotnet: 2.2.203

install:
  - dotnet restore

script:
  - dotnet build -c Release

deploy:
  - provider: script
    skip-cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master
      tags: true
  - provider: script
    skip-cleanup: true
    script: bash scripts/patch-version.sh && bash scripts/deploy.sh
    on:
      branch: master
      tags: false

  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: src/TeamSpeak3QueryApi/bin/Release/*.nupkg
    skip_cleanup: true
    on:
      branch: master
      tags: true
